import pytest
from unittest.mock import patch, PropertyMock
from pathlib import Path
from bindu.extensions.did.did_agent_extension import DIDAgentExtension
from bindu.settings import app_settings

@pytest.fixture
def did_extension(tmp_path):
    # Setup extension with temporary key directory
    key_dir = tmp_path / "keys"
    key_dir.mkdir()
    ext = DIDAgentExtension(
        recreate_keys=True,
        key_dir=key_dir,
        author="test_author",
        agent_name="test_agent",
        agent_id="test_id"
    )
    # Ensure keys are generated
    ext.generate_and_save_key_pair()
    return ext

def test_validate_keys_success(did_extension):
    # Should not raise exception
    did_extension.validate_keys()

def test_validate_keys_failure(did_extension):
    # Generate another key pair to get a mismatched public key
    other_dir = did_extension._key_dir / "other"
    other_dir.mkdir()
    
    other_ext = DIDAgentExtension(
        recreate_keys=True,
        key_dir=other_dir,
        author="other",
        agent_name="other",
        agent_id="other"
    )
    other_ext.generate_and_save_key_pair()
    
    # Overwrite the original public key with the other one
    did_extension.public_key_path.write_bytes(other_ext.public_key_path.read_bytes())
    
    # Must clear cached property to reload from file
    if "public_key" in did_extension.__dict__:
        del did_extension.__dict__["public_key"]

    with pytest.raises(ValueError, match="Private key does not match public key"):
        did_extension.validate_keys()

def test_check_integrity_success(did_extension):
    # By default, generated DID document might not have service endpoints unless added
    # But usually integrity check validates existing things.
    # If no endpoints, it should pass if keys are valid.
    
    # We need to ensure get_did_document returns something validatable.
    # The default get_did_document implementation in DIDAgentExtension doesn't seem to add services by default
    # unless metadata is modified.
    
    # Let's start with basic integrity (keys and structure)
    try:
        did_extension.check_integrity()
    except Exception as e:
        pytest.fail(f"check_integrity failed unexpectedly: {e}")

def test_check_integrity_endpoint_mismatch(did_extension):
    # Inject a service endpoint into the DID extension metadata that doesn't match default_url
    
    # First, mock default_url
    with patch('bindu.settings.NetworkSettings.default_url', new_callable=PropertyMock) as mock_url:
        mock_url.return_value = "http://localhost:8000"
        
        # We need to manually add a service to the DID document generated by the extension.
        # Looking at DIDAgentExtension, get_did_document() returns a dict.
        # But check_integrity calls self.get_did_document().
        # We can mock get_did_document or modify how it constructs the document if possible.
        # DIDAgentExtension has a 'metadata' attribute but get_did_document implementation 
        # (checked earlier) only uses minimal fields.
        
        # Let's subclass or mock get_did_document to return a doc with service endpoint
        original_get_doc = did_extension.get_did_document
        
        def mock_get_doc():
            doc = original_get_doc()
            doc["service"] = [{
                "id": f"{did_extension.did}#agent",
                "type": "AgentService",
                "serviceEndpoint": "http://evil.com"
            }]
            return doc
            
        did_extension.get_did_document = mock_get_doc
        
        with pytest.raises(ValueError, match="Service endpoint http://evil.com does not match"):
            did_extension.check_integrity()

def test_check_integrity_endpoint_match(did_extension):
    # Verify it passes when endpoint matches
    with patch('bindu.settings.NetworkSettings.default_url', new_callable=PropertyMock) as mock_url:
        target_url = "http://myserver.com:8000"
        mock_url.return_value = target_url
        
        original_get_doc = did_extension.get_did_document
        
        def mock_get_doc():
            doc = original_get_doc()
            doc["service"] = [{
                "id": f"{did_extension.did}#agent",
                "type": "AgentService",
                # Validation should be robust to trailing slashes
                "serviceEndpoint": target_url + "/"
            }]
            return doc
            
        did_extension.get_did_document = mock_get_doc
        
        did_extension.check_integrity()
